# Generated by Django 5.2.7 on 2025-10-12 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def set_default_created_by(apps, schema_editor):
    """Set a default created_by for existing events"""
    Event = apps.get_model('events', 'Event')
    User = apps.get_model(settings.AUTH_USER_MODEL)
    
    # Get the first superuser or create a default user
    try:
        default_user = User.objects.filter(is_superuser=True).first()
        if not default_user:
            # If no superuser exists, get the first user
            default_user = User.objects.first()
        
        if default_user:
            # Update all existing events to have this user as created_by
            Event.objects.filter(created_by__isnull=True).update(created_by=default_user)
    except:
        # If no users exist, we'll handle this in the next migration
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Rename 'name' field to 'title'
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='title',
        ),
        
        # Remove the old 'tags' field (string-based)
        migrations.RemoveField(
            model_name='event',
            name='tags',
        ),
        
        # Add created_by field as nullable first
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='created_events',
                to=settings.AUTH_USER_MODEL,
                help_text="User who created this event"
            ),
        ),
        
        # Run the data migration to set default values
        migrations.RunPython(set_default_created_by, migrations.RunPython.noop),
        
        # Now make created_by non-nullable
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='created_events',
                to=settings.AUTH_USER_MODEL,
                help_text="User who created this event"
            ),
        ),
        
        # Update other fields with help text and constraints
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, help_text="Event title"),
        ),
        
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text="Event description"),
        ),
        
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(help_text="Event date and time"),
        ),
        
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=200, help_text="Event location"),
        ),
        
        # Add database indexes
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date'], name='events_event_date_idx'),
        ),
        
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_by'], name='events_event_created_by_idx'),
        ),
        
        # Add Meta options
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
    ]
