# Generated by Django 5.2.7 on 2025-10-15 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_update_event_model"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="event",
            new_name="events_even_date_5e8e1c_idx",
            old_name="events_event_date_idx",
        ),
        migrations.RenameIndex(
            model_name="event",
            new_name="events_even_created_95418c_idx",
            old_name="events_event_created_by_idx",
        ),
    ]
