# Generated by Django 5.1.6 on 2025-07-29 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectdomain",
            name="domain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.domain"
            ),
        ),
        migrations.AddField(
            model_name="projectdomain",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="projects.project"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="domains",
            field=models.ManyToManyField(
                through="projects.ProjectDomain", to="users.domain"
            ),
        ),
        migrations.AddField(
            model_name="projectteammember",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="projects.project"
            ),
        ),
        migrations.AddField(
            model_name="projectteammember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="team_members",
            field=models.ManyToManyField(
                related_name="projects",
                through="projects.ProjectTeamMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectdomain",
            unique_together={("project", "domain")},
        ),
        migrations.AlterUniqueTogether(
            name="projectteammember",
            unique_together={("project", "user")},
        ),
    ]
