# Generated by Django 5.2.7 on 2026-03-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_project_github_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="github_link",
            field=models.URLField(default="https://github.com/CSESA-IITI"),
            preserve_default=False,
        ),
    ]
