# Generated by Django 5.2.4 on 2025-07-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_is_onboarded"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="picture",
            field=models.URLField(
                blank=True,
                help_text="URL of the user's Google profile picture",
                null=True,
            ),
        ),
    ]
