# Generated by Django 5.2.7 on 2025-10-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="admission_year",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="instagram_link",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="picture",
        ),
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="department",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="year",
            field=models.CharField(
                blank=True, help_text="Graduation Year", max_length=4
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("PRESIDENT", "President"),
                    ("HEAD", "Head"),
                    ("COORDINATOR", "Coordinator"),
                    ("ASSOCIATE", "Associate"),
                ],
                default="ASSOCIATE",
                max_length=50,
            ),
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="skills",
        ),
        migrations.AddField(
            model_name="customuser",
            name="skills",
            field=models.ManyToManyField(blank=True, to="users.skill"),
        ),
    ]
