# Generated by Django 5.2.7 on 2025-10-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_skill_remove_customuser_admission_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="domain",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMPETITIVE_PROGRAMMING", "Competitive Programming"),
                    ("WEB_DEVELOPMENT", "Web Development"),
                    ("SYSTEMS_PROGRAMMING", "Systems Programming"),
                    ("GRAPHICS_PROGRAMMING", "Graphics Programming"),
                    ("MACHINE_LEARNING", "Machine Learning"),
                ],
                max_length=50,
            ),
        ),
    ]
