# Generated by Django 5.2.7 on 2025-10-13 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_customuser_domain"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="department",
        ),
    ]
